# Generated by Django 3.0.8 on 2021-01-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='original',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
