# Generated by Django 3.0.8 on 2021-01-16 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0003_auto_20210116_2040'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentProduct',
        ),
    ]
