# Generated by Django 3.0.8 on 2021-01-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_delete_commentproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='summary',
            new_name='cross',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='features',
            new_name='shipping',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='users_like',
        ),
        migrations.RemoveField(
            model_name='product',
            name='views',
        ),
        migrations.AddField(
            model_name='product',
            name='original',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
