# Generated by Django 3.0.8 on 2021-01-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0005_auto_20210116_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='instock',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
