# Generated by Django 3.0.8 on 2021-02-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0006_product_instock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produceer', models.CharField(max_length=60)),
                ('index', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('original', models.TextField()),
                ('instock', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10000)),
            ],
        ),
    ]
