# Generated by Django 3.0.8 on 2021-02-09 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0007_product2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product2',
            old_name='produceer',
            new_name='producer',
        ),
    ]
