# Generated by Django 3.0.8 on 2021-03-07 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0020_auto_20210307_1524'),
        ('parts', '0008_auto_20210209_1526'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product2',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='cross',
            new_name='index',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='producer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='author',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='publish',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shipping',
        ),
    ]
