# Generated by Django 3.0.8 on 2021-02-07 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='owener',
            new_name='owner',
        ),
    ]
