# Generated by Django 3.0.8 on 2021-02-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0006_product_instock'),
        ('cart', '0003_auto_20210207_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(null=True, to='parts.Product'),
        ),
    ]
