# Generated by Django 3.0.8 on 2021-02-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20210207_2036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='is_ordered',
            new_name='in_order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_ordered',
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('ORD', 'Ordered'), ('PRP', 'Preparing order'), ('SHP', 'Shipping'), ('DLV', 'Delivered')], default='ORD', max_length=3),
        ),
    ]
