# Generated by Django 3.0.8 on 2021-02-10 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parts', '0008_auto_20210209_1526'),
        ('cart', '0007_auto_20210209_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_order', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('part', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parts.Product2')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='cart.CartItem'),
        ),
    ]
