# Generated by Django 3.0.8 on 2021-02-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0008_auto_20210209_1526'),
        ('cart', '0008_auto_20210210_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='part',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='part',
            field=models.ManyToManyField(to='parts.Product2'),
        ),
    ]
