# Generated by Django 3.0.8 on 2021-02-10 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0008_auto_20210209_1526'),
        ('cart', '0010_auto_20210210_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parts.Product2'),
        ),
    ]
