# Generated by Django 3.0.8 on 2021-02-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_auto_20210210_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('ORD', 'Ordered'), ('PRP', 'Preparing order'), ('SHP', 'Shipping'), ('DLV', 'Delivered')], default='INC', max_length=3),
        ),
    ]
