# Generated by Django 3.0.8 on 2021-02-16 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_shippingdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingdata',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.Order'),
        ),
    ]
