# Generated by Django 3.0.8 on 2021-02-16 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_shippingdata_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingdata',
            name='city',
            field=models.CharField(max_length=40, verbose_name='Місто/Село'),
        ),
        migrations.AlterField(
            model_name='shippingdata',
            name='name',
            field=models.CharField(max_length=30, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='shippingdata',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+380999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Номер телефону'),
        ),
        migrations.AlterField(
            model_name='shippingdata',
            name='surname',
            field=models.CharField(max_length=30, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='shippingdata',
            name='viddil',
            field=models.IntegerField(verbose_name='Відділ НП'),
        ),
    ]
