# Generated by Django 3.0.8 on 2021-02-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0017_auto_20210216_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingdata',
            name='date_ordered',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
