# Generated by Django 3.0.8 on 2021-02-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0018_shippingdata_date_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shippingdata',
            name='date_ordered',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
